name: Hello World (in a Docker)
author: Daniel Czarnievicz
description: An action that greets
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'Mr Smith'
outputs:
  time:
    description: Greeting time
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
