name: Shell commands
on: workflow_dispatch
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
