name: Variables
on: workflow_dispatch
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
