name: Create a file with a random number
on: push
jobs:
  create-random-number:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Create a file with a random number
        run: |
          pwd
          ls -a
          git config --global init.defaultBranch main
          git init
          git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m "Random file"
          git push
