name: My JS action
on: workflow_dispatch
jobs:
  test-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Say hello
        id: hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: 'World'
      - name: Verify action run
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
